src/Project/Website/code/Models/SearchModel.cs
using Sitecore.ContentSearch;
using Sitecore.ContentSearch.SearchTypes;
using System;
using System.Collections.Generic;
namespace HW.Models
{
    public class SearchModel : SearchResultItem
    {
        [IndexField("title_t")]
        public virtual string Title { get; set; }
        [IndexField("short_t")]
        public virtual string Short { get; set; }
        [IndexField("date_t")]
        public virtual DateTime Date { get; set; }
        [IndexField("image_t")]
        public virtual string Image { get; set; }


    }
    public class SearchResult
    {
        public string Title { get; set; }
        public string Short { get; set; }
        public string Url { get; set; }
        public string Date { get; set; }
        public virtual string Image { get; set; }
    }
    /// <summary>
    /// Custom search result model for binding to front end
    /// </summary>
    public class SearchResults
    {
        public List<SearchResult> Results { get; set; }
    }
}

src/Project/Website/code/Controllers/SolrIndexController.cs
using HW.Models;
using Sitecore.ContentSearch;
using Sitecore.ContentSearch.Linq;
using Sitecore.ContentSearch.Linq.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web.Mvc;

namespace HW.Controllers
{
    public class SolrIndexController : Controller
    {
        public ActionResult DoSearch(string searchText)
        {
            var myResults = new SearchResults
            {
                Results = new List<SearchResult>()
            };
            var searchIndex = ContentSearchManager.GetIndex("sitecore_web_index"); // Get the search index
            var searchPredicate = GetSearchPredicate(searchText); // Build the search predicate
            using (var searchContext = searchIndex.CreateSearchContext()) // Get a context of the search index
            {
                //Select * from Sitecore_web_index Where Author="searchText" OR Description = "searchText" OR Title = "searchText"
                var searchResults = searchContext.GetQueryable<SearchModel>().Where(searchPredicate); // Search the index for items which match the predicate

                // This will get all of the results, which is not reccomended
                var fullResults = searchResults.GetResults();
                // This is better and will get paged results - page 1 with 10 results per page
                 //var pagedResults = searchResults.Page(1, 10).GetResults();
                foreach (var hit in fullResults.Hits)
                {
                    Sitecore.Data.Fields.ImageField ifd = hit.Document.GetItem().Fields["Image"];
                    Sitecore.Data.Items.MediaItem img = new Sitecore.Data.Items.MediaItem(ifd.MediaItem); 
                    string imgsrc = Sitecore.StringUtil.EnsurePrefix('/',Sitecore.Resources.Media.MediaManager.GetMediaUrl(img));
                    myResults.Results.Add(new SearchResult
                    {
                        Title = hit.Document.Title,
                        Short = hit.Document.Short,
                        Date = hit.Document.Date.ToShortDateString(),
                        Url = hit.Document.GetItem().Paths.Path,
                        Image = imgsrc
                    });
                }
                return new JsonResult
                {
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                    Data = myResults
                };
            }
        }
        /// <summary>
        /// Search logic
        /// </summary>
        /// <param name="searchText">Search term</param>
        /// <returns>Search predicate object</returns>
        public static Expression<Func<SearchModel, bool>> GetSearchPredicate(string searchText)
            {
                var predicate = PredicateBuilder.False<SearchModel>(); // Items which meet the predicate
                predicate = predicate.Or(x => x.Short.Contains(searchText)); // .Boost(2.0f);
                predicate = predicate.Or(x => x.Title.Contains(searchText)); // .Boost(2.0f);
                predicate = predicate.And(x => !String.IsNullOrEmpty(x.Short)); // .Boost(2.0f);
                                                                             //Where Author="searchText" OR Description="searchText" OR Title="searchText"
                return predicate;
            }
    }
}

src/Project/Website/code/Views/HW/ArticleBody.cshtml
<main role="main" class="container blog-post-detail">
	<script type="text/javascript">
		var tags = "@Html.Sitecore().Field("tags")".split(',');
		$(document).ready(function () {
			var tags = "@Html.Sitecore().Field("tags")";
			$('tagListCntnr').css('display', tags ? 'block' : 'none');
			$('#tagsList').text();
            $('#tagsList').append(
				tags.split(',').map(x=> `<a class="btn btn-info" href="#" role="button">${x}</a>`)
			);
		});
	</script>
	<div class="row">
		<div class="blog-post-detail-card card col-lg-12">
			@Html.Sitecore().Field("image")
			<div class="card-body bg-light">
				<strong class="d-inline-block mb-2 text-success">Design</strong>
				<h3 class="card-title">@Html.Sitecore().Field("title") </h3>
				<div class="mb-1 text-muted">@Html.Sitecore().Field("date") </div>
				@Html.Sitecore().Field("Text")
				<div class="blog-detail-tag-list" id="tagsList" id="tagListCntnr">
					<span class="read-more-heading">Read more: </span>
					<span id="tagsList"></span>
				</div>
			</div>
		</div>
	</div>
</main>

src/Project/Website/code/Views/HW/DefaultLayout.cshtml
@using Sitecore.Mvc
@using Sitecore.Mvc.Analytics.Extensions
<!DOCTYPE html>
@{
    Sitecore.Data.Database master = Sitecore.Configuration.Factory.GetDatabase("master");
    Sitecore.Data.Items.Item bsItem = master.GetItem("/sitecore/media library/Files/css/bootstrap-themedmin"),
        bsMedia = new Sitecore.Data.Items.MediaItem(bsItem),
        blgItem = master.GetItem("/sitecore/media library/Files/css/blogsite"),
        blgMedia = new Sitecore.Data.Items.MediaItem(blgItem);
    string bsUrl = Sitecore.StringUtil.EnsurePrefix('/', Sitecore.Resources.Media.MediaManager.GetMediaUrl(bsMedia)),
        blgUrl = Sitecore.StringUtil.EnsurePrefix('/', Sitecore.Resources.Media.MediaManager.GetMediaUrl(blgMedia));
}
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
        <link rel="stylesheet" href="~/assets/css/bootstrap-themed.min.css">
        <link rel="stylesheet" href="~/assets/css/blogsite.css">
    </head>
    <body>
        @Html.Sitecore().Placeholder("phMain")
    </body>
</html>

src/Project/Website/code/Views/HW/Footer.cshtml
@{ 
    var item = Sitecore.Context.Database.GetItem("{E838BC5D-B7ED-4227-B69E-6827F9783DC3}");
}
<footer>
	<div class="container">
	  <div class="text-white bg-primary">
        <p class="lead">@Html.Sitecore().Field("Copyright", item)</p>
	  </div>
	</div>
</footer>

src/Project/Website/code/Views/HW/Header.cshtml
@{ 
    var item = Sitecore.Context.Database.GetItem("{E838BC5D-B7ED-4227-B69E-6827F9783DC3}");
}
<header>
    <div class="container">
      <div class="jumbotron text-white @RenderingContext.Current.Rendering.Parameters["cls"]">
        <h1 class="display-3">@Html.Sitecore().Field("SiteTitle", item)</h1>
        <p class="lead">@Html.Sitecore().Field("SubTitle", item)</p>
      </div>
    </div>
  </header>

src/Project/Website/code/Views/HW/Search.cshtml
@{
    ViewBag.Title = "SOLR Search Component";
}

<main role="main" class="container blog-posts">
  
	<div class="main-search">
			<div class="input-group">
			<input type="text" name="name" id="searchInput" required placeholder="Search this blog">
			<div class="input-group-append">
		
			<button type="button" id="searchButton" class="btn btn-dark">@Sitecore.Globalization.Translate.Text("cmdSearch")</button>
			
			</div>
		</div>
	</div>
  
  
	<br>
  
    <div class="row" id="resultsItem">
    </div>
</main>

<script>
		$(document).ready(function () {
			$("#searchButton").click(function (e) {
				e.preventDefault();
				$.ajax({
					type: "GET",
					datatype: "JSON", url: "@Url.Action("DoSearch", "SolrIndex")",
					contentType: "application/json",
					data: {
						searchText: $("#searchInput").val()
					},
					success: function (result) {
						var resultText = "";
						$('#resultsItem').text(resultText);
						$(result.Results).each(function (index, item) {
							// each iteration
							var url = item.Url.replace(/^.*\/HW\//, '/');
							resultText += `
								<div class="blog-post-card card col-lg-4 col-md-6">
									<img class="card-img-top" src="${item.Image}" alt="Card image cap" style="width: 100%;">
									<div class="card-body bg-light ">
										<strong class="d-inline-block mb-2 text-success">Design</strong>
										<h3 class="card-title">${item.Title}</h3>
										<div class="mb-1 text-muted">${item.Date}</div>
										${item.Short}
										<a href="${url}" class="btn btn-warning btn-block">Read on</a>
									</div>
								</div>
							`;

						});
						$('#resultsItem').append(resultText);
					},
					error: function (result) {
						alert('error');
					}
				});
			});
		});
</script>